### ISSUE TITLE
fTextBox1.Text

### ISSUE THREAD

**Issue by techishow** [0xLaileb/WinForms.FC_UI#1]
Hello , im trying to use the textbox with this arguments ==> fTextBox1.Text to see and read the text on textbox with other elements but they cant read it ! its like fTextBox1.Text dosent work and there is no text on it !!
its working with normal textbox !
can you help me pls ?

**Comment by 0xLaileb** [comment]
> Hello , im trying to use the textbox with this arguments ==> fTextBox1.Text to see and read the text on textbox with other elements but they cant read it ! its like fTextBox1.Text dosent work and there is no text on it !!
> its working with normal textbox !
> can you help me pls ?

**Hi, my friend**, I immediately apologize for my English (I use a translator).

This project is temporarily abandoned, in the future I want to rewrite it under WPF, I also recommend that you switch to WPF (you can use https://github.com/HandyOrg/HandyControl).

I will try to solve your problem, please attach me a sample code that you can show.

**Comment by 0xLaileb** [comment]
Ohhh, I seem to understand what you mean, I fixed it: **https://github.com/Lako-FC/FC_UI/commit/71923bb31dedc34456e234fbcbe1f37814aeeb9c**

Download the source code and build the project: **https://github.com/Lako-FC/FC_UI/archive/master.zip**

_- Please write down if it helped you or not._

**Comment by techishow** [comment]
source = source.Replace("#processtext", textBox2.Text);
                source = source.Replace("#commandtext", textBox1.Text);

**Comment by techishow** [comment]
im trying replace something with the ftextbox but its not working ! i compiled the source and still get the same problem

**Comment by 0xLaileb** [comment]
> ```
>             source = source.Replace("#processtext", textBox2.Text);
>             source = source.Replace("#commandtext", textBox1.Text);
> ```

Use ftextbox.TextButton pls:
`source = source.Replace("#processtext", textBox2.TextButton);`

This working?
